<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Plan.Data\Plan.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\plan.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Kromě ikony .exe je potřeba i jako Resource, aby si ji mohla vzít okna aplikace. -->
    <Resource Include="Resources\plan.ico" />
  </ItemGroup>

</Project>
