// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plan.Data;

#nullable disable

namespace Plan.Data.Migrations
{
    [DbContext(typeof(PlanDbContext))]
    [Migration("20260808201648_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Plan.Data.Entities.NastaveniZaznam", b =>
                {
                    b.Property<string>("Klic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hodnota")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Klic");

                    b.ToTable("Nastaveni", (string)null);
                });

            modelBuilder.Entity("Plan.Data.Entities.Zakazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DatumDo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DatumOd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpravenoUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatumOd");

                    b.ToTable("Zakazky", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
